# app.py
import streamlit as st
import requests
import json
from sdk.watermark import verify_image_manifest_bytes  # uses your existing SDK; unchanged

# Page config
st.set_page_config(page_title="Reke Demo", page_icon="🛡️", layout="centered")

# Styling: white outlined buttons
st.markdown(
    """
    <style>
    /* White outlined select buttons */
    div.stButton > button:first-child {
        background-color: white !important;
        color: black !important;
        border: 1px solid black !important;
        border-radius: 6px !important;
        padding: 0.35em 0.9em !important;
        font-weight: 600 !important;
    }
    div.stButton > button:first-child:hover {
        background-color: #f7f7f7 !important;
    }
    /* Emphasise verify button */
    .verify-button button {
        font-size: 18px !important;
        padding: 0.5em 1.4em !important;
    }
    .thumb-grid { display:flex; gap:12px; flex-wrap:wrap; justify-content:center; }
    .thumb-box { width:160px; text-align:center; }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("🛡️ Reke — Demo (Select a sample and Verify)")

# --- Sample images (AI ones should be detected by SDK) ---
SAMPLES = {
    # AI (these should be detected as AI-generated by your SDK)
    "ai_model": "https://ul.postcrest.com/90uqa61eksfuzyj8uppr50be8tsj.png?format=webp&width=1664",
    "ai_painter": "https://preview.redd.it/ai-images-are-getting-too-realistic-v0-nxue8y4zt9be1.png?width=1080&crop=smart&auto=webp&s=a3f70deb45f4f4d50c09f8ffa439a83b05504440",
    "ai_panda_chimp": "https://preview.redd.it/ai-images-are-getting-too-realistic-v0-sejwvqqzt9be1.png?width=1080&crop=smart&auto=webp&s=1a44b93bd8f02cd7f6fa98dc7ba08ef500e1adfb",
    "ai_woman": "https://preview.redd.it/ai-images-are-getting-too-realistic-v0-l2zp3ra0u9be1.png?width=1080&crop=smart&auto=webp&s=f4bde879ffc48fc635e84b865cac6ff485471acd",

    # Real (these should be detected as Real / no watermark)
    "real_cat": "https://images.wallpaperscraft.com/image/single/kitten_cat_tree_146608_938x1668.jpg",
    "real_child": "https://img.freepik.com/free-photo/laughing-girl-climbing-ropes_1328677.jpg",
    "real_dog": "https://cdn.sanity.io/images/4ij0poqn/production/3806e8982db7e74f828bb2039e6394cf0139b4d0-800x600.jpg",
    "real_man": "https://img.freepik.com/free-photo/side-view-man-painting-canvas_23-2150170489.jpg",
    "real_woman": "https://img.freepik.com/free-photo/portrait-young-attractive-emotional-girl-dressed-trendy-blue-denim-coat_1153-3942.jpg",
}

# Ensure session state keys exist
if "selected_key" not in st.session_state:
    st.session_state["selected_key"] = None
if "selected_url" not in st.session_state:
    st.session_state["selected_url"] = None

st.write("Click any image to select it (use the white 'Select' button). Then click **Verify Image** to run the Reke API / SDK check.")
st.write("**Note:** Uploads are disabled in this demo — only these curated samples can be used to showcase the flow.")

# Thumbnail grid
st.markdown('<div class="thumb-grid">', unsafe_allow_html=True)
for key, url in SAMPLES.items():
    # each thumbnail with a Select button under it
    st.markdown(f'<div class="thumb-box">', unsafe_allow_html=True)
    try:
        st.image(url, width=160, caption="")  # use_column_width not used in thumbnails
    except Exception:
        # fallback: simple broken image placeholder
        st.write("[image unavailable]")
    if st.button("Select", key=f"btn_{key}"):
        st.session_state["selected_key"] = key
        st.session_state["selected_url"] = url
    st.markdown("</div>", unsafe_allow_html=True)
st.markdown('</div>', unsafe_allow_html=True)

st.markdown("---")

# Main preview area
if st.session_state["selected_url"]:
    st.subheader("Selected image")
    # Use `use_column_width=True` (correct kwarg)
    st.image(st.session_state["selected_url"], use_column_width=True)

    # Verify button
    if st.button("Verify Image", key="verify_btn"):
        with st.spinner("Verifying (calling SDK)..."):
            # Download bytes
            try:
                r = requests.get(st.session_state["selected_url"], timeout=20)
                r.raise_for_status()
                img_bytes = r.content
            except Exception as e:
                st.error(f"Could not download the image for verification: {e}")
                img_bytes = None

            if img_bytes:
                # Call your SDK verify function (unchanged watermark logic)
                try:
                    status, manifest, sig_ok = verify_image_manifest_bytes(img_bytes)
                except Exception as e:
                    st.error(f"SDK threw an exception during verify: {e}")
                    status, manifest, sig_ok = "Unknown", None, False

                # Present results clearly
                if status == "AI Generated":
                    st.markdown('<div style="background:#fff0f0;padding:12px;border-left:6px solid #ff4d4d;border-radius:6px">', unsafe_allow_html=True)
                    st.markdown("### 🚨 AI Generated — Watermark detected")
                    st.markdown("</div>", unsafe_allow_html=True)
                elif status == "Real":
                    st.markdown('<div style="background:#f0fff4;padding:12px;border-left:6px solid #00b341;border-radius:6px">', unsafe_allow_html=True)
                    st.markdown("### ✅ Real — No watermark found")
                    st.markdown("</div>", unsafe_allow_html=True)
                else:
                    st.info("❓ Result unknown or signature invalid")

                st.write("**Signature valid:**", bool(sig_ok))
                st.write("**SDK manifest (if present):**")
                if manifest:
                    try:
                        st.json(manifest)
                    except Exception:
                        st.write(manifest)
                else:
                    st.write("No manifest embedded (image not watermarked).")
else:
    st.info("No sample selected — use the Select buttons under any sample to choose an image.")

st.markdown("---")
st.caption(
    "Demo: AI samples contain a synthetic Reke watermark. Real samples are plain. "
    "Future versions will include Tree-Ring watermarking, C2PA provenance, screenshot tamper resistance, and global SDK integration with AI generators and platform APIs."
)
